events {}

http {
    server {
        listen 80;

        # Serve static files from frontend
        location / {
            proxy_pass http://frontend:80;
        }

        # Proxy API requests to Flask app
        location /api/ {
            proxy_pass http://weather_app:5000;
        }
    }
}