apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-data-pvc
  namespace: weather
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
