apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SasunIspiryan/weather_aggregator.git
    targetRevision: 2e464a5e395fea5520cbfb12ded36856247275fe
    path: weather-chart
    helm:
      values: |
        replicaCount: 2
        image:
          repository: sasunispiryan/weather_aggregator
          tag: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: weather
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
