replicaCount: 2
image:
  repository: weather-backend
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 5000
ingress:
  enabled: true
  host: weather.local
config:
  dbHost: "postgres-service"
  appEnv: "production"
  logLevel: "info"
db:
  secretName: weather-db-creds
