apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-creds
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
  DB_USER: d2VhdGhlcg==
